import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../app/providers.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_layout.dart';
import '../../../core/utils/moz_phone_utils.dart';
import '../../../core/widgets/app_feedback.dart';
import '../../../core/errors/app_error_mapper.dart';
import '../../../design_system/design_system.dart';
import '../../auth/presentation/auth_controller.dart';
import '../data/affiliate_dao.dart';
import '../data/affiliate_repository.dart';
import '../domain/affiliate_code.dart';
import '../domain/merchant_affiliate_dtos.dart';
import '../providers/affiliate_providers.dart';
import '../services/affiliate_share_message.dart';
import 'widgets/affiliate_widgets.dart';

/// Adds an affiliate and mints their code in one step.
///
/// The code is not something the owner chooses. It is generated by the server
/// in the same transaction that creates the link, which is what makes it unique
/// across the platform — so this form collects who the person is and what their
/// code should be worth, and the code itself arrives as an answer.
class AffiliateCreateScreen extends ConsumerStatefulWidget {
  const AffiliateCreateScreen({super.key});

  @override
  ConsumerState<AffiliateCreateScreen> createState() =>
      _AffiliateCreateScreenState();
}

class _AffiliateCreateScreenState extends ConsumerState<AffiliateCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _phoneCtrl = TextEditingController();
  final _valueCtrl = TextEditingController(text: '50');
  final _limitCtrl = TextEditingController();

  /// The plan's defaults, and the ones the backend would apply anyway.
  ReferralBenefitType _benefitType = ReferralBenefitType.fixedAmount;
  bool _firstVisitOnly = true;
  int _expiryDays = 30;

  bool _submitting = false;
  MerchantAffiliate? _created;
  ProvisionalAffiliate? _queued;

  @override
  void dispose() {
    _nameCtrl.dispose();
    _phoneCtrl.dispose();
    _valueCtrl.dispose();
    _limitCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_submitting) return;
    if (!(_formKey.currentState?.validate() ?? false)) return;

    final value = double.tryParse(_valueCtrl.text.replaceAll(',', '.'));
    if (value == null) return;
    final rawLimit = _limitCtrl.text.trim();
    final limit = rawLimit.isEmpty ? null : int.tryParse(rawLimit);
    final draft = AffiliateDraft(
      name: _nameCtrl.text.trim(),
      phone: MozPhoneUtils.normalizeToE164(_phoneCtrl.text.trim()),
      benefitType: _benefitType.storageValue,
      benefitValue: value,
      usageLimit: limit,
      firstVisitOnly: _firstVisitOnly,
      expiresAt: DateTime.now().add(Duration(days: _expiryDays)),
    );

    final online = ref.read(isOnlineProvider).valueOrNull ?? true;
    if (!online) {
      await _submitOffline(draft);
      return;
    }

    setState(() => _submitting = true);
    try {
      final created = await ref
          .read(affiliateAdminControllerProvider.notifier)
          .createAffiliate(draft);
      if (!mounted) return;
      setState(() => _created = created);
      AppFeedback.showSuccessToast(
        context,
        message: 'Afiliado adicionado',
        subtitle: 'O código já pode ser partilhado.',
      );
    } catch (error) {
      if (!mounted) return;
      AppFeedback.showMessage(
        context,
        message: AppErrorMapper.describe(error).message,
        isError: true,
      );
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  /// Adds the affiliate here and asks the server later.
  ///
  /// The owner gets a usable record and an honest one: the code on screen is
  /// this device's own, marked as such, and sharing is not offered at all. A
  /// provisional code handed to somebody would be typed at a counter and
  /// refused, with the affiliate standing there.
  Future<void> _submitOffline(AffiliateDraft draft) async {
    final repository = ref.read(affiliateOfflineGatewayProvider);
    if (repository == null) {
      AppFeedback.showMessage(
        context,
        message: 'Este dispositivo ainda não está identificado. '
            'Ligue-o ao negócio para adicionar afiliados.',
        isError: true,
      );
      return;
    }

    setState(() => _submitting = true);
    try {
      final queued = await repository.createAffiliateOffline(draft);
      if (!mounted) return;
      setState(() => _queued = queued);
      AppFeedback.showMessage(
        context,
        message: 'Afiliado guardado. O código definitivo chega quando '
            'houver ligação.',
      );
    } catch (error) {
      if (!mounted) return;
      AppFeedback.showMessage(
        context,
        message: AppErrorMapper.describe(error).message,
        isError: true,
      );
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isOwner = ref.watch(isOwnerUserProvider).valueOrNull ?? false;
    final online = ref.watch(isOnlineProvider).valueOrNull ?? true;
    final created = _created;
    final queued = _queued;

    return Scaffold(
      backgroundColor: AppColors.surface,
      appBar: const MaisUmAppBar(title: 'Adicionar afiliado'),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: AppLayout.formMaxWidth),
            child: created != null
                ? _CreatedPanel(affiliate: created)
                : queued != null
                    ? _ProvisionalPanel(affiliate: queued)
                    : _buildForm(isOwner: isOwner, online: online),
          ),
        ),
      ),
    );
  }

  Widget _buildForm({required bool isOwner, required bool online}) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (!online) ...[
            const AffiliateOfflineNotice(
              key: Key('affiliate-create-offline-notice'),
              message: 'Sem ligação. O afiliado fica guardado neste aparelho '
                  'com um código provisório, que não pode ser partilhado até '
                  'o sistema confirmar o código definitivo.',
            ),
            const SizedBox(height: AppSpacing.md),
          ],
          if (!isOwner) ...[
            const AffiliateOfflineNotice(
              message: 'Só o responsável do negócio pode adicionar afiliados.',
            ),
            const SizedBox(height: AppSpacing.md),
          ],
          // There is one business per signed-in session, so there is nothing to
          // choose between. Naming it is still worth a line: it is the business
          // whose points this code will spend.
          _BusinessContext(
            name: ref.watch(authControllerProvider).valueOrNull?.merchantName ??
                'O seu negócio',
          ),
          const SizedBox(height: AppSpacing.lg),
          MaisUmTextField(
            fieldKey: const Key('affiliate-name-field'),
            controller: _nameCtrl,
            label: 'Nome',
            hintText: 'Ex.: Ana Silva',
            textCapitalization: TextCapitalization.words,
            validator: (value) {
              final name = value?.trim() ?? '';
              if (name.length < 2) return 'Escreva o nome do afiliado';
              return null;
            },
          ),
          const SizedBox(height: AppSpacing.md),
          MaisUmTextField(
            fieldKey: const Key('affiliate-phone-field'),
            controller: _phoneCtrl,
            label: 'Telemóvel',
            hintText: '8X XXX XXXX',
            keyboardType: TextInputType.phone,
            validator: MozPhoneUtils.validatorMessage,
          ),
          const SizedBox(height: AppSpacing.xl),
          const _SectionLabel('Benefício do cliente'),
          const SizedBox(height: AppSpacing.sm),
          _BenefitTypeSelector(
            selected: _benefitType,
            onChanged: (type) => setState(() => _benefitType = type),
          ),
          const SizedBox(height: AppSpacing.md),
          MaisUmTextField(
            fieldKey: const Key('affiliate-benefit-value-field'),
            controller: _valueCtrl,
            label: _benefitLabel,
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            inputFormatters: [
              FilteringTextInputFormatter.allow(RegExp(r'[\d,.]')),
            ],
            validator: _validateBenefitValue,
          ),
          const SizedBox(height: AppSpacing.xl),
          const _SectionLabel('Regras do código'),
          const SizedBox(height: AppSpacing.sm),
          MaisUmTextField(
            fieldKey: const Key('affiliate-usage-limit-field'),
            controller: _limitCtrl,
            label: 'Limite de usos (opcional)',
            hintText: 'Deixe vazio para não ter limite',
            keyboardType: TextInputType.number,
            inputFormatters: [FilteringTextInputFormatter.digitsOnly],
            validator: (value) {
              final raw = value?.trim() ?? '';
              if (raw.isEmpty) return null;
              final parsed = int.tryParse(raw);
              if (parsed == null || parsed < 1 || parsed > 100000) {
                return 'Use um número entre 1 e 100000';
              }
              return null;
            },
          ),
          const SizedBox(height: AppSpacing.md),
          _ExpirySelector(
            days: _expiryDays,
            onChanged: (days) => setState(() => _expiryDays = days),
          ),
          const SizedBox(height: AppSpacing.md),
          SwitchListTile.adaptive(
            key: const Key('affiliate-first-visit-switch'),
            value: _firstVisitOnly,
            onChanged: (value) => setState(() => _firstVisitOnly = value),
            contentPadding: EdgeInsets.zero,
            title: const Text('Só na primeira visita'),
            subtitle: const Text(
              'Recomendado. Mantém o código para trazer clientes novos.',
            ),
          ),
          const SizedBox(height: AppSpacing.xl),
          MaisUmButton(
            key: const Key('affiliate-create-submit'),
            label: 'Adicionar afiliado',
            loadingLabel: 'A adicionar…',
            isLoading: _submitting,
            onPressed: isOwner && !_submitting ? _submit : null,
            animationDuration: Duration.zero,
          ),
        ],
      ),
    );
  }

  String get _benefitLabel => switch (_benefitType) {
        ReferralBenefitType.percentage => 'Percentagem de desconto (1 a 50)',
        ReferralBenefitType.fixedAmount => 'Desconto em MT',
        ReferralBenefitType.points => 'Pontos oferecidos',
      };

  String? _validateBenefitValue(String? raw) {
    final value = double.tryParse((raw ?? '').replaceAll(',', '.'));
    if (value == null || value <= 0) return 'Escreva um valor maior que zero';
    return switch (_benefitType) {
      ReferralBenefitType.percentage => value < 1 || value > 50
          ? 'A percentagem tem de estar entre 1 e 50'
          : null,
      ReferralBenefitType.fixedAmount =>
        value > 1000000 ? 'Valor demasiado alto' : null,
      ReferralBenefitType.points => value != value.roundToDouble()
          ? 'Os pontos têm de ser um número inteiro'
          : value > 100000
              ? 'Valor demasiado alto'
              : null,
    };
  }
}

class _BusinessContext extends StatelessWidget {
  const _BusinessContext({required this.name});

  final String name;

  @override
  Widget build(BuildContext context) {
    return MaisUmSurface(
      variant: MaisUmSurfaceVariant.muted,
      radius: AppRadius.md,
      padding: const EdgeInsets.all(AppSpacing.md),
      animationDuration: Duration.zero,
      child: Row(
        children: [
          const Icon(Icons.storefront_rounded,
              size: 18, color: AppColors.primary),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Text(
              'Negócio: $name',
              style: const TextStyle(color: AppColors.onSurfaceVariant),
            ),
          ),
        ],
      ),
    );
  }
}

class _SectionLabel extends StatelessWidget {
  const _SectionLabel(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      header: true,
      child: Text(
        text,
        style: const TextStyle(
          fontWeight: FontWeight.w800,
          color: AppColors.onSurface,
        ),
      ),
    );
  }
}

class _BenefitTypeSelector extends StatelessWidget {
  const _BenefitTypeSelector({required this.selected, required this.onChanged});

  final ReferralBenefitType selected;
  final ValueChanged<ReferralBenefitType> onChanged;

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: AppSpacing.sm,
      runSpacing: AppSpacing.sm,
      children: [
        for (final type in ReferralBenefitType.values)
          ChoiceChip(
            label: Text(_label(type)),
            selected: selected == type,
            onSelected: (_) => onChanged(type),
            padding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.md,
              vertical: AppSpacing.sm,
            ),
          ),
      ],
    );
  }

  static String _label(ReferralBenefitType type) => switch (type) {
        ReferralBenefitType.percentage => 'Percentagem',
        ReferralBenefitType.fixedAmount => 'Valor em MT',
        ReferralBenefitType.points => 'Pontos',
      };
}

class _ExpirySelector extends StatelessWidget {
  const _ExpirySelector({required this.days, required this.onChanged});

  final int days;
  final ValueChanged<int> onChanged;

  static const _options = <int>[30, 60, 90, 180];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Validade do código',
          style: TextStyle(color: AppColors.onSurfaceVariant),
        ),
        const SizedBox(height: AppSpacing.sm),
        Wrap(
          spacing: AppSpacing.sm,
          runSpacing: AppSpacing.sm,
          children: [
            for (final option in _options)
              ChoiceChip(
                label: Text('$option dias'),
                selected: days == option,
                onSelected: (_) => onChanged(option),
                padding: const EdgeInsets.symmetric(
                  horizontal: AppSpacing.md,
                  vertical: AppSpacing.sm,
                ),
              ),
          ],
        ),
      ],
    );
  }
}

/// The confirmation for an affiliate that exists only on this device.
///
/// Says the code is provisional, shows it so the owner recognises the row in
/// the list, and offers no way to share it. The contrast with [_CreatedPanel]
/// is the point: one of these codes works at a counter and the other does not.
class _ProvisionalPanel extends StatelessWidget {
  const _ProvisionalPanel({required this.affiliate});

  final ProvisionalAffiliate affiliate;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        MaisUmSurface(
          key: const Key('affiliate-provisional-panel'),
          variant: MaisUmSurfaceVariant.warning,
          radius: AppRadius.lg,
          padding: const EdgeInsets.all(AppSpacing.lg),
          animationDuration: Duration.zero,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(Icons.schedule_rounded, color: AppColors.warning),
                  const SizedBox(width: AppSpacing.sm),
                  Expanded(
                    child: Text(
                      '${affiliate.displayName} guardado neste aparelho',
                      style: const TextStyle(
                        fontWeight: FontWeight.w800,
                        color: AppColors.onSurface,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.lg),
              const Text(
                'Código provisório',
                style: TextStyle(color: AppColors.onSurfaceVariant),
              ),
              const SizedBox(height: AppSpacing.xs),
              SelectableText(
                affiliate.provisionalCode,
                key: const Key('affiliate-provisional-code'),
                style: const TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1.5,
                  color: AppColors.onSurface,
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: AppSpacing.lg),
        const AffiliateOfflineNotice(
          key: Key('affiliate-provisional-share-blocked'),
          message: 'Este código ainda não está confirmado pelo sistema, por '
              'isso não pode ser partilhado. Quando houver ligação, o código '
              'definitivo substitui este e fica pronto a partilhar.',
        ),
        const SizedBox(height: AppSpacing.md),
        const MaisUmButton(
          key: Key('affiliate-share-button-disabled'),
          label: 'Partilhar código',
          leadingIcon: Icons.share_rounded,
          onPressed: null,
          animationDuration: Duration.zero,
        ),
        const SizedBox(height: AppSpacing.md),
        MaisUmButton(
          label: 'Ver afiliados',
          variant: MaisUmButtonVariant.outlined,
          foregroundColor: AppColors.primary,
          onPressed: () => context.pushReplacement('/affiliates'),
          animationDuration: Duration.zero,
        ),
      ],
    );
  }
}

/// The confirmation, with the code the server actually minted.
///
/// Sharing is only offered once that code exists and is usable. A provisional
/// code — one this device invented while offline — is never shareable, because
/// the person who receives it would type it at the counter and be refused.
class _CreatedPanel extends ConsumerWidget {
  const _CreatedPanel({required this.affiliate});

  final MerchantAffiliate affiliate;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final code = affiliate.code;
    final businessName =
        ref.watch(authControllerProvider).valueOrNull?.merchantName ?? '';
    final draft = buildAffiliateShareDraft(
      affiliate: affiliate,
      businessName: businessName,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        MaisUmSurface(
          key: const Key('affiliate-created-panel'),
          variant: MaisUmSurfaceVariant.success,
          radius: AppRadius.lg,
          padding: const EdgeInsets.all(AppSpacing.lg),
          animationDuration: Duration.zero,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(Icons.check_circle_rounded,
                      color: AppColors.success),
                  const SizedBox(width: AppSpacing.sm),
                  Expanded(
                    child: Text(
                      '${affiliate.name} é agora afiliado',
                      style: const TextStyle(
                        fontWeight: FontWeight.w800,
                        color: AppColors.onSurface,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.lg),
              const Text(
                'Código confirmado',
                style: TextStyle(color: AppColors.onSurfaceVariant),
              ),
              const SizedBox(height: AppSpacing.xs),
              SelectableText(
                code?.code.toUpperCase() ?? '—',
                key: const Key('affiliate-created-code'),
                style: const TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1.5,
                  color: AppColors.onSurface,
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: AppSpacing.lg),
        if (draft == null)
          const AffiliateOfflineNotice(
            message: 'Este código ainda não está confirmado pelo sistema, '
                'por isso não pode ser partilhado.',
          ),
        if (draft != null)
          MaisUmButton(
            key: const Key('affiliate-share-button'),
            label: 'Partilhar código',
            leadingIcon: Icons.share_rounded,
            onPressed: () => _share(context, draft),
            animationDuration: Duration.zero,
          ),
        const SizedBox(height: AppSpacing.md),
        MaisUmButton(
          label: 'Ver afiliado',
          variant: MaisUmButtonVariant.outlined,
          foregroundColor: AppColors.primary,
          onPressed: () => context.pushReplacement(
            '/affiliates/${affiliate.id}',
          ),
          animationDuration: Duration.zero,
        ),
      ],
    );
  }

  Future<void> _share(BuildContext context, AffiliateShareDraft draft) async {
    final launched = await launchUrl(
      draft.uri,
      mode: LaunchMode.externalApplication,
    );
    if (!launched && context.mounted) {
      AppFeedback.showMessage(
        context,
        message: 'Não foi possível abrir o WhatsApp.',
        isError: true,
      );
    }
  }
}
