// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=loyaltyos-fc4dd
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiD3ozFKrqrfP7nyeb3bYX8kYLB2wpAUs',
    appId: '1:517299605672:android:392da87b191d830cc7329d',
    messagingSenderId: '517299605672',
    projectId: 'loyaltyos-fc4dd',
    storageBucket: 'loyaltyos-fc4dd.firebasestorage.app',
  );
}
