# Deploy static content to Firebase Hosting
name: Deploy static content to Firebase Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "firebase-hosting"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: production
      url: https://maisum.tsintsivadigital.com/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOYALTYOS_FC4DD }}
          channelId: live
          projectId: loyaltyos-fc4dd
